services:
  coasterpediatools:
    image: ghcr.io/coasterpedia/coasterpedia-tools/tools@${API_IMAGE}
    restart: always
    networks:
      - coasterpedia_web
    environment:
      ConnectionStrings__DefaultConnection: ${DEFAULT_CONNECTION_STRING}
      OAuthConfig__ClientId: ${OAUTH_CLIENT_ID}
      OAuthConfig__ClientSecret: ${OAUTH_CLIENT_SECRET}
      CommonsConfig__AccessToken: ${COMMONS_ACCESS_TOKEN}
    ports:
      - 9003:8080
networks:
  coasterpedia_web:
    external: true